version: "3"
services:
  user-timeline-redis:
    network_mode: bridge
    image: redis
    hostname: user-timeline-redis
    #    ports:
    #      - 6383:6379
    restart: always
    command: /social-network-microservices/config/redis.conf
    volumes:
      - ../config:/social-network-microservices/config
      - ../keys:/keys
    extra_hosts:
      - "social-graph-service:172.17.0.1"
      - "compose-post-service:172.17.0.1"
      - "post-storage-service:172.17.0.1"      
      - "user-timeline-service:172.17.0.1"
      - "url-shorten-service:172.17.0.1"
      - "user-service:172.17.0.1"
      - "media-service:172.17.0.1"
      - "text-service:172.17.0.1"
      - "unique-id-service:172.17.0.1"
      - "user-mention-service:172.17.0.1"
      - "home-timeline-service:172.17.0.1"