--
-- Autogenerated by Thrift
--
-- DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
-- @generated
--


require 'Thrift'
require 'social_network_ttypes'

UserMentionServiceClient = __TObject.new(__TClient, {
  __type = 'UserMentionServiceClient'
})

function UserMentionServiceClient:ComposeUserMentions(req_id, usernames)
  self:send_ComposeUserMentions(req_id, usernames)
  return self:recv_ComposeUserMentions(req_id, usernames)
end

function UserMentionServiceClient:send_ComposeUserMentions(req_id, usernames)
  self.oprot:writeMessageBegin('ComposeUserMentions', TMessageType.CALL, self._seqid)
  local args = ComposeUserMentions_args:new{}
  args.req_id = req_id
  args.usernames = usernames
  args:write(self.oprot)
  self.oprot:writeMessageEnd()
  self.oprot.trans:flush()
end

function UserMentionServiceClient:recv_ComposeUserMentions(req_id, usernames)
  local fname, mtype, rseqid = self.iprot:readMessageBegin()
  if mtype == TMessageType.EXCEPTION then
    local x = TApplicationException:new{}
    x:read(self.iprot)
    self.iprot:readMessageEnd()
    error(x)
  end
  local result = ComposeUserMentions_result:new{}
  result:read(self.iprot)
  self.iprot:readMessageEnd()
  if result.success ~= nil then
    return result.success
  elseif result.se then
    error(result.se)
  end
  error(TApplicationException:new{errorCode = TApplicationException.MISSING_RESULT})
end
UserMentionServiceIface = __TObject:new{
  __type = 'UserMentionServiceIface'
}


UserMentionServiceProcessor = __TObject.new(__TProcessor
, {
 __type = 'UserMentionServiceProcessor'
})

function UserMentionServiceProcessor:process(iprot, oprot, server_ctx)
  local name, mtype, seqid = iprot:readMessageBegin()
  local func_name = 'process_' .. name
  if not self[func_name] or ttype(self[func_name]) ~= 'function' then
    iprot:skip(TType.STRUCT)
    iprot:readMessageEnd()
    x = TApplicationException:new{
      errorCode = TApplicationException.UNKNOWN_METHOD
    }
    oprot:writeMessageBegin(name, TMessageType.EXCEPTION, seqid)
    x:write(oprot)
    oprot:writeMessageEnd()
    oprot.trans:flush()
  else
    self[func_name](self, seqid, iprot, oprot, server_ctx)
  end
end

function UserMentionServiceProcessor:process_ComposeUserMentions(seqid, iprot, oprot, server_ctx)
  local args = ComposeUserMentions_args:new{}
  local reply_type = TMessageType.REPLY
  args:read(iprot)
  iprot:readMessageEnd()
  local result = ComposeUserMentions_result:new{}
  local status, res = pcall(self.handler.ComposeUserMentions, self.handler, args.req_id, args.usernames)
  if not status then
    reply_type = TMessageType.EXCEPTION
    result = TApplicationException:new{message = res}
  elseif ttype(res) == 'ServiceException' then
    result.se = res
  else
    result.success = res
  end
  oprot:writeMessageBegin('ComposeUserMentions', reply_type, seqid)
  result:write(oprot)
  oprot:writeMessageEnd()
  oprot.trans:flush()
end

-- HELPER FUNCTIONS AND STRUCTURES

ComposeUserMentions_args = __TObject:new{
  req_id,
  usernames
}

function ComposeUserMentions_args:read(iprot)
  iprot:readStructBegin()
  while true do
    local fname, ftype, fid = iprot:readFieldBegin()
    if ftype == TType.STOP then
      break
    elseif fid == 1 then
      if ftype == TType.I64 then
        self.req_id = iprot:readI64()
      else
        iprot:skip(ftype)
      end
    elseif fid == 2 then
      if ftype == TType.LIST then
        self.usernames = {}
        local _etype87, _size84 = iprot:readListBegin()
        for _i=1,_size84 do
          local _elem88 = iprot:readString()
          table.insert(self.usernames, _elem88)
        end
        iprot:readListEnd()
      else
        iprot:skip(ftype)
      end
    else
      iprot:skip(ftype)
    end
    iprot:readFieldEnd()
  end
  iprot:readStructEnd()
end

function ComposeUserMentions_args:write(oprot)
  oprot:writeStructBegin('ComposeUserMentions_args')
  if self.req_id ~= nil then
    oprot:writeFieldBegin('req_id', TType.I64, 1)
    oprot:writeI64(self.req_id)
    oprot:writeFieldEnd()
  end
  if self.usernames ~= nil then
    oprot:writeFieldBegin('usernames', TType.LIST, 2)
    oprot:writeListBegin(TType.STRING, #self.usernames)
    for _,iter89 in ipairs(self.usernames) do
      oprot:writeString(iter89)
    end
    oprot:writeListEnd()
    oprot:writeFieldEnd()
  end
  oprot:writeFieldStop()
  oprot:writeStructEnd()
end

ComposeUserMentions_result = __TObject:new{
  success,
  se
}

function ComposeUserMentions_result:read(iprot)
  iprot:readStructBegin()
  while true do
    local fname, ftype, fid = iprot:readFieldBegin()
    if ftype == TType.STOP then
      break
    elseif fid == 0 then
      if ftype == TType.LIST then
        self.success = {}
        local _etype93, _size90 = iprot:readListBegin()
        for _i=1,_size90 do
          local _elem94 = UserMention:new{}
          _elem94:read(iprot)
          table.insert(self.success, _elem94)
        end
        iprot:readListEnd()
      else
        iprot:skip(ftype)
      end
    elseif fid == 1 then
      if ftype == TType.STRUCT then
        self.se = ServiceException:new{}
        self.se:read(iprot)
      else
        iprot:skip(ftype)
      end
    else
      iprot:skip(ftype)
    end
    iprot:readFieldEnd()
  end
  iprot:readStructEnd()
end

function ComposeUserMentions_result:write(oprot)
  oprot:writeStructBegin('ComposeUserMentions_result')
  if self.success ~= nil then
    oprot:writeFieldBegin('success', TType.LIST, 0)
    oprot:writeListBegin(TType.STRUCT, #self.success)
    for _,iter95 in ipairs(self.success) do
      iter95:write(oprot)
    end
    oprot:writeListEnd()
    oprot:writeFieldEnd()
  end
  if self.se ~= nil then
    oprot:writeFieldBegin('se', TType.STRUCT, 1)
    self.se:write(oprot)
    oprot:writeFieldEnd()
  end
  oprot:writeFieldStop()
  oprot:writeStructEnd()
end