version: "3"
services:
  user-memcached:
    network_mode: bridge
    image: memcached
    hostname: user-memcached
    #    ports:
    #      - 11214:11211
    restart: always
    extra_hosts:
      - "social-graph-service:172.17.0.1"
      - "compose-post-service:172.17.0.1"
      - "post-storage-service:172.17.0.1"      
      - "user-timeline-service:172.17.0.1"
      - "url-shorten-service:172.17.0.1"
      - "user-service:172.17.0.1"
      - "media-service:172.17.0.1"
      - "text-service:172.17.0.1"
      - "unique-id-service:172.17.0.1"
      - "user-mention-service:172.17.0.1"
      - "home-timeline-service:172.17.0.1"