/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ComposePostService_H
#define ComposePostService_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include "social_network_types.h"

namespace social_network {

#ifdef _MSC_VER
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class ComposePostServiceIf {
 public:
  virtual ~ComposePostServiceIf() {}
  virtual void ComposePost(const int64_t req_id, const std::string& username, const int64_t user_id, const std::string& text, const std::vector<int64_t> & media_ids, const std::vector<std::string> & media_types, const PostType::type post_type) = 0;
  virtual void StorePost(const int64_t req_id, const Post& post) = 0;
  virtual void ReadPost(Post& _return, const int64_t req_id, const int64_t post_id) = 0;
  virtual void ReadPosts(std::vector<Post> & _return, const int64_t req_id, const std::vector<int64_t> & post_ids) = 0;
};

class ComposePostServiceIfFactory {
 public:
  typedef ComposePostServiceIf Handler;

  virtual ~ComposePostServiceIfFactory() {}

  virtual ComposePostServiceIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(ComposePostServiceIf* /* handler */) = 0;
};

class ComposePostServiceIfSingletonFactory : virtual public ComposePostServiceIfFactory {
 public:
  ComposePostServiceIfSingletonFactory(const ::apache::thrift::stdcxx::shared_ptr<ComposePostServiceIf>& iface) : iface_(iface) {}
  virtual ~ComposePostServiceIfSingletonFactory() {}

  virtual ComposePostServiceIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(ComposePostServiceIf* /* handler */) {}

 protected:
  ::apache::thrift::stdcxx::shared_ptr<ComposePostServiceIf> iface_;
};

class ComposePostServiceNull : virtual public ComposePostServiceIf {
 public:
  virtual ~ComposePostServiceNull() {}
  void ComposePost(const int64_t /* req_id */, const std::string& /* username */, const int64_t /* user_id */, const std::string& /* text */, const std::vector<int64_t> & /* media_ids */, const std::vector<std::string> & /* media_types */, const PostType::type /* post_type */) {
    return;
  }
  void StorePost(const int64_t /* req_id */, const Post& /* post */) {
    return;
  }
  void ReadPost(Post& /* _return */, const int64_t /* req_id */, const int64_t /* post_id */) {
    return;
  }
  void ReadPosts(std::vector<Post> & /* _return */, const int64_t /* req_id */, const std::vector<int64_t> & /* post_ids */) {
    return;
  }
};

typedef struct _ComposePostService_ComposePost_args__isset {
  _ComposePostService_ComposePost_args__isset() : req_id(false), username(false), user_id(false), text(false), media_ids(false), media_types(false), post_type(false) {}
  bool req_id :1;
  bool username :1;
  bool user_id :1;
  bool text :1;
  bool media_ids :1;
  bool media_types :1;
  bool post_type :1;
} _ComposePostService_ComposePost_args__isset;

class ComposePostService_ComposePost_args {
 public:

  ComposePostService_ComposePost_args(const ComposePostService_ComposePost_args&);
  ComposePostService_ComposePost_args& operator=(const ComposePostService_ComposePost_args&);
  ComposePostService_ComposePost_args() : req_id(0), username(), user_id(0), text(), post_type((PostType::type)0) {
  }

  virtual ~ComposePostService_ComposePost_args() throw();
  int64_t req_id;
  std::string username;
  int64_t user_id;
  std::string text;
  std::vector<int64_t>  media_ids;
  std::vector<std::string>  media_types;
  PostType::type post_type;

  _ComposePostService_ComposePost_args__isset __isset;

  void __set_req_id(const int64_t val);

  void __set_username(const std::string& val);

  void __set_user_id(const int64_t val);

  void __set_text(const std::string& val);

  void __set_media_ids(const std::vector<int64_t> & val);

  void __set_media_types(const std::vector<std::string> & val);

  void __set_post_type(const PostType::type val);

  bool operator == (const ComposePostService_ComposePost_args & rhs) const
  {
    if (!(req_id == rhs.req_id))
      return false;
    if (!(username == rhs.username))
      return false;
    if (!(user_id == rhs.user_id))
      return false;
    if (!(text == rhs.text))
      return false;
    if (!(media_ids == rhs.media_ids))
      return false;
    if (!(media_types == rhs.media_types))
      return false;
    if (!(post_type == rhs.post_type))
      return false;
    return true;
  }
  bool operator != (const ComposePostService_ComposePost_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ComposePostService_ComposePost_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class ComposePostService_ComposePost_pargs {
 public:


  virtual ~ComposePostService_ComposePost_pargs() throw();
  const int64_t* req_id;
  const std::string* username;
  const int64_t* user_id;
  const std::string* text;
  const std::vector<int64_t> * media_ids;
  const std::vector<std::string> * media_types;
  const PostType::type* post_type;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ComposePostService_ComposePost_result__isset {
  _ComposePostService_ComposePost_result__isset() : se(false) {}
  bool se :1;
} _ComposePostService_ComposePost_result__isset;

class ComposePostService_ComposePost_result {
 public:

  ComposePostService_ComposePost_result(const ComposePostService_ComposePost_result&);
  ComposePostService_ComposePost_result& operator=(const ComposePostService_ComposePost_result&);
  ComposePostService_ComposePost_result() {
  }

  virtual ~ComposePostService_ComposePost_result() throw();
  ServiceException se;

  _ComposePostService_ComposePost_result__isset __isset;

  void __set_se(const ServiceException& val);

  bool operator == (const ComposePostService_ComposePost_result & rhs) const
  {
    if (!(se == rhs.se))
      return false;
    return true;
  }
  bool operator != (const ComposePostService_ComposePost_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ComposePostService_ComposePost_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ComposePostService_ComposePost_presult__isset {
  _ComposePostService_ComposePost_presult__isset() : se(false) {}
  bool se :1;
} _ComposePostService_ComposePost_presult__isset;

class ComposePostService_ComposePost_presult {
 public:


  virtual ~ComposePostService_ComposePost_presult() throw();
  ServiceException se;

  _ComposePostService_ComposePost_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _ComposePostService_StorePost_args__isset {
  _ComposePostService_StorePost_args__isset() : req_id(false), post(false) {}
  bool req_id :1;
  bool post :1;
} _ComposePostService_StorePost_args__isset;

class ComposePostService_StorePost_args {
 public:

  ComposePostService_StorePost_args(const ComposePostService_StorePost_args&);
  ComposePostService_StorePost_args& operator=(const ComposePostService_StorePost_args&);
  ComposePostService_StorePost_args() : req_id(0) {
  }

  virtual ~ComposePostService_StorePost_args() throw();
  int64_t req_id;
  Post post;

  _ComposePostService_StorePost_args__isset __isset;

  void __set_req_id(const int64_t val);

  void __set_post(const Post& val);

  bool operator == (const ComposePostService_StorePost_args & rhs) const
  {
    if (!(req_id == rhs.req_id))
      return false;
    if (!(post == rhs.post))
      return false;
    return true;
  }
  bool operator != (const ComposePostService_StorePost_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ComposePostService_StorePost_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class ComposePostService_StorePost_pargs {
 public:


  virtual ~ComposePostService_StorePost_pargs() throw();
  const int64_t* req_id;
  const Post* post;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ComposePostService_StorePost_result__isset {
  _ComposePostService_StorePost_result__isset() : se(false) {}
  bool se :1;
} _ComposePostService_StorePost_result__isset;

class ComposePostService_StorePost_result {
 public:

  ComposePostService_StorePost_result(const ComposePostService_StorePost_result&);
  ComposePostService_StorePost_result& operator=(const ComposePostService_StorePost_result&);
  ComposePostService_StorePost_result() {
  }

  virtual ~ComposePostService_StorePost_result() throw();
  ServiceException se;

  _ComposePostService_StorePost_result__isset __isset;

  void __set_se(const ServiceException& val);

  bool operator == (const ComposePostService_StorePost_result & rhs) const
  {
    if (!(se == rhs.se))
      return false;
    return true;
  }
  bool operator != (const ComposePostService_StorePost_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ComposePostService_StorePost_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ComposePostService_StorePost_presult__isset {
  _ComposePostService_StorePost_presult__isset() : se(false) {}
  bool se :1;
} _ComposePostService_StorePost_presult__isset;

class ComposePostService_StorePost_presult {
 public:


  virtual ~ComposePostService_StorePost_presult() throw();
  ServiceException se;

  _ComposePostService_StorePost_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _ComposePostService_ReadPost_args__isset {
  _ComposePostService_ReadPost_args__isset() : req_id(false), post_id(false) {}
  bool req_id :1;
  bool post_id :1;
} _ComposePostService_ReadPost_args__isset;

class ComposePostService_ReadPost_args {
 public:

  ComposePostService_ReadPost_args(const ComposePostService_ReadPost_args&);
  ComposePostService_ReadPost_args& operator=(const ComposePostService_ReadPost_args&);
  ComposePostService_ReadPost_args() : req_id(0), post_id(0) {
  }

  virtual ~ComposePostService_ReadPost_args() throw();
  int64_t req_id;
  int64_t post_id;

  _ComposePostService_ReadPost_args__isset __isset;

  void __set_req_id(const int64_t val);

  void __set_post_id(const int64_t val);

  bool operator == (const ComposePostService_ReadPost_args & rhs) const
  {
    if (!(req_id == rhs.req_id))
      return false;
    if (!(post_id == rhs.post_id))
      return false;
    return true;
  }
  bool operator != (const ComposePostService_ReadPost_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ComposePostService_ReadPost_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class ComposePostService_ReadPost_pargs {
 public:


  virtual ~ComposePostService_ReadPost_pargs() throw();
  const int64_t* req_id;
  const int64_t* post_id;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ComposePostService_ReadPost_result__isset {
  _ComposePostService_ReadPost_result__isset() : success(false), se(false) {}
  bool success :1;
  bool se :1;
} _ComposePostService_ReadPost_result__isset;

class ComposePostService_ReadPost_result {
 public:

  ComposePostService_ReadPost_result(const ComposePostService_ReadPost_result&);
  ComposePostService_ReadPost_result& operator=(const ComposePostService_ReadPost_result&);
  ComposePostService_ReadPost_result() {
  }

  virtual ~ComposePostService_ReadPost_result() throw();
  Post success;
  ServiceException se;

  _ComposePostService_ReadPost_result__isset __isset;

  void __set_success(const Post& val);

  void __set_se(const ServiceException& val);

  bool operator == (const ComposePostService_ReadPost_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    if (!(se == rhs.se))
      return false;
    return true;
  }
  bool operator != (const ComposePostService_ReadPost_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ComposePostService_ReadPost_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ComposePostService_ReadPost_presult__isset {
  _ComposePostService_ReadPost_presult__isset() : success(false), se(false) {}
  bool success :1;
  bool se :1;
} _ComposePostService_ReadPost_presult__isset;

class ComposePostService_ReadPost_presult {
 public:


  virtual ~ComposePostService_ReadPost_presult() throw();
  Post* success;
  ServiceException se;

  _ComposePostService_ReadPost_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _ComposePostService_ReadPosts_args__isset {
  _ComposePostService_ReadPosts_args__isset() : req_id(false), post_ids(false) {}
  bool req_id :1;
  bool post_ids :1;
} _ComposePostService_ReadPosts_args__isset;

class ComposePostService_ReadPosts_args {
 public:

  ComposePostService_ReadPosts_args(const ComposePostService_ReadPosts_args&);
  ComposePostService_ReadPosts_args& operator=(const ComposePostService_ReadPosts_args&);
  ComposePostService_ReadPosts_args() : req_id(0) {
  }

  virtual ~ComposePostService_ReadPosts_args() throw();
  int64_t req_id;
  std::vector<int64_t>  post_ids;

  _ComposePostService_ReadPosts_args__isset __isset;

  void __set_req_id(const int64_t val);

  void __set_post_ids(const std::vector<int64_t> & val);

  bool operator == (const ComposePostService_ReadPosts_args & rhs) const
  {
    if (!(req_id == rhs.req_id))
      return false;
    if (!(post_ids == rhs.post_ids))
      return false;
    return true;
  }
  bool operator != (const ComposePostService_ReadPosts_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ComposePostService_ReadPosts_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class ComposePostService_ReadPosts_pargs {
 public:


  virtual ~ComposePostService_ReadPosts_pargs() throw();
  const int64_t* req_id;
  const std::vector<int64_t> * post_ids;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ComposePostService_ReadPosts_result__isset {
  _ComposePostService_ReadPosts_result__isset() : success(false), se(false) {}
  bool success :1;
  bool se :1;
} _ComposePostService_ReadPosts_result__isset;

class ComposePostService_ReadPosts_result {
 public:

  ComposePostService_ReadPosts_result(const ComposePostService_ReadPosts_result&);
  ComposePostService_ReadPosts_result& operator=(const ComposePostService_ReadPosts_result&);
  ComposePostService_ReadPosts_result() {
  }

  virtual ~ComposePostService_ReadPosts_result() throw();
  std::vector<Post>  success;
  ServiceException se;

  _ComposePostService_ReadPosts_result__isset __isset;

  void __set_success(const std::vector<Post> & val);

  void __set_se(const ServiceException& val);

  bool operator == (const ComposePostService_ReadPosts_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    if (!(se == rhs.se))
      return false;
    return true;
  }
  bool operator != (const ComposePostService_ReadPosts_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ComposePostService_ReadPosts_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ComposePostService_ReadPosts_presult__isset {
  _ComposePostService_ReadPosts_presult__isset() : success(false), se(false) {}
  bool success :1;
  bool se :1;
} _ComposePostService_ReadPosts_presult__isset;

class ComposePostService_ReadPosts_presult {
 public:


  virtual ~ComposePostService_ReadPosts_presult() throw();
  std::vector<Post> * success;
  ServiceException se;

  _ComposePostService_ReadPosts_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class ComposePostServiceClient : virtual public ComposePostServiceIf {
 public:
  ComposePostServiceClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  ComposePostServiceClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void ComposePost(const int64_t req_id, const std::string& username, const int64_t user_id, const std::string& text, const std::vector<int64_t> & media_ids, const std::vector<std::string> & media_types, const PostType::type post_type);
  void send_ComposePost(const int64_t req_id, const std::string& username, const int64_t user_id, const std::string& text, const std::vector<int64_t> & media_ids, const std::vector<std::string> & media_types, const PostType::type post_type);
  void recv_ComposePost();
  void StorePost(const int64_t req_id, const Post& post);
  void send_StorePost(const int64_t req_id, const Post& post);
  void recv_StorePost();
  void ReadPost(Post& _return, const int64_t req_id, const int64_t post_id);
  void send_ReadPost(const int64_t req_id, const int64_t post_id);
  void recv_ReadPost(Post& _return);
  void ReadPosts(std::vector<Post> & _return, const int64_t req_id, const std::vector<int64_t> & post_ids);
  void send_ReadPosts(const int64_t req_id, const std::vector<int64_t> & post_ids);
  void recv_ReadPosts(std::vector<Post> & _return);
 protected:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class ComposePostServiceProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  ::apache::thrift::stdcxx::shared_ptr<ComposePostServiceIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (ComposePostServiceProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_ComposePost(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_StorePost(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_ReadPost(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_ReadPosts(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  ComposePostServiceProcessor(::apache::thrift::stdcxx::shared_ptr<ComposePostServiceIf> iface) :
    iface_(iface) {
    processMap_["ComposePost"] = &ComposePostServiceProcessor::process_ComposePost;
    processMap_["StorePost"] = &ComposePostServiceProcessor::process_StorePost;
    processMap_["ReadPost"] = &ComposePostServiceProcessor::process_ReadPost;
    processMap_["ReadPosts"] = &ComposePostServiceProcessor::process_ReadPosts;
  }

  virtual ~ComposePostServiceProcessor() {}
};

class ComposePostServiceProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  ComposePostServiceProcessorFactory(const ::apache::thrift::stdcxx::shared_ptr< ComposePostServiceIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::apache::thrift::stdcxx::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::apache::thrift::stdcxx::shared_ptr< ComposePostServiceIfFactory > handlerFactory_;
};

class ComposePostServiceMultiface : virtual public ComposePostServiceIf {
 public:
  ComposePostServiceMultiface(std::vector<apache::thrift::stdcxx::shared_ptr<ComposePostServiceIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~ComposePostServiceMultiface() {}
 protected:
  std::vector<apache::thrift::stdcxx::shared_ptr<ComposePostServiceIf> > ifaces_;
  ComposePostServiceMultiface() {}
  void add(::apache::thrift::stdcxx::shared_ptr<ComposePostServiceIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void ComposePost(const int64_t req_id, const std::string& username, const int64_t user_id, const std::string& text, const std::vector<int64_t> & media_ids, const std::vector<std::string> & media_types, const PostType::type post_type) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->ComposePost(req_id, username, user_id, text, media_ids, media_types, post_type);
    }
    ifaces_[i]->ComposePost(req_id, username, user_id, text, media_ids, media_types, post_type);
  }

  void StorePost(const int64_t req_id, const Post& post) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->StorePost(req_id, post);
    }
    ifaces_[i]->StorePost(req_id, post);
  }

  void ReadPost(Post& _return, const int64_t req_id, const int64_t post_id) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->ReadPost(_return, req_id, post_id);
    }
    ifaces_[i]->ReadPost(_return, req_id, post_id);
    return;
  }

  void ReadPosts(std::vector<Post> & _return, const int64_t req_id, const std::vector<int64_t> & post_ids) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->ReadPosts(_return, req_id, post_ids);
    }
    ifaces_[i]->ReadPosts(_return, req_id, post_ids);
    return;
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class ComposePostServiceConcurrentClient : virtual public ComposePostServiceIf {
 public:
  ComposePostServiceConcurrentClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  ComposePostServiceConcurrentClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void ComposePost(const int64_t req_id, const std::string& username, const int64_t user_id, const std::string& text, const std::vector<int64_t> & media_ids, const std::vector<std::string> & media_types, const PostType::type post_type);
  int32_t send_ComposePost(const int64_t req_id, const std::string& username, const int64_t user_id, const std::string& text, const std::vector<int64_t> & media_ids, const std::vector<std::string> & media_types, const PostType::type post_type);
  void recv_ComposePost(const int32_t seqid);
  void StorePost(const int64_t req_id, const Post& post);
  int32_t send_StorePost(const int64_t req_id, const Post& post);
  void recv_StorePost(const int32_t seqid);
  void ReadPost(Post& _return, const int64_t req_id, const int64_t post_id);
  int32_t send_ReadPost(const int64_t req_id, const int64_t post_id);
  void recv_ReadPost(Post& _return, const int32_t seqid);
  void ReadPosts(std::vector<Post> & _return, const int64_t req_id, const std::vector<int64_t> & post_ids);
  int32_t send_ReadPosts(const int64_t req_id, const std::vector<int64_t> & post_ids);
  void recv_ReadPosts(std::vector<Post> & _return, const int32_t seqid);
 protected:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  ::apache::thrift::async::TConcurrentClientSyncInfo sync_;
};

#ifdef _MSC_VER
  #pragma warning( pop )
#endif

} // namespace

#endif
