/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ComposePostService_H
#define ComposePostService_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include "social_network_types.h"

namespace social_network {

#ifdef _MSC_VER
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class ComposePostServiceIf {
 public:
  virtual ~ComposePostServiceIf() {}
  virtual void ComposePost(const int64_t req_id, const std::string& username, const int64_t user_id, const std::string& text, const std::vector<int64_t> & media_ids, const std::vector<std::string> & media_types, const PostType::type post_type) = 0;
  virtual void StorePost(const int64_t req_id, const Post& post) = 0;
  virtual void ReadPost(Post& _return, const int64_t req_id, const int64_t post_id) = 0;
  virtual void ReadPosts(std::vector<Post> & _return, const int64_t req_id, const std::vector<int64_t> & post_ids) = 0;
  virtual void ReadUserTimeline(std::vector<Post> & _return, const int64_t req_id, const int64_t user_id, const int32_t start, const int32_t stop) = 0;
  virtual void Login(std::string& _return, const int64_t req_id, const std::string& username, const std::string& password) = 0;
  virtual void RegisterUser(const int64_t req_id, const std::string& first_name, const std::string& last_name, const std::string& username, const std::string& password) = 0;
  virtual void RegisterUserWithId(const int64_t req_id, const std::string& first_name, const std::string& last_name, const std::string& username, const std::string& password, const int64_t user_id) = 0;
  virtual void GetFollowers(std::vector<int64_t> & _return, const int64_t req_id, const int64_t user_id) = 0;
  virtual void Unfollow(const int64_t req_id, const int64_t user_id, const int64_t followee_id) = 0;
  virtual void UnfollowWithUsername(const int64_t req_id, const std::string& user_usernmae, const std::string& followee_username) = 0;
  virtual void Follow(const int64_t req_id, const int64_t user_id, const int64_t followee_id) = 0;
  virtual void FollowWithUsername(const int64_t req_id, const std::string& user_usernmae, const std::string& followee_username) = 0;
  virtual void GetFollowees(std::vector<int64_t> & _return, const int64_t req_id, const int64_t user_id) = 0;
  virtual void ReadHomeTimeline(std::vector<Post> & _return, const int64_t req_id, const int64_t user_id, const int32_t start, const int32_t stop) = 0;
};

class ComposePostServiceIfFactory {
 public:
  typedef ComposePostServiceIf Handler;

  virtual ~ComposePostServiceIfFactory() {}

  virtual ComposePostServiceIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(ComposePostServiceIf* /* handler */) = 0;
};

class ComposePostServiceIfSingletonFactory : virtual public ComposePostServiceIfFactory {
 public:
  ComposePostServiceIfSingletonFactory(const ::apache::thrift::stdcxx::shared_ptr<ComposePostServiceIf>& iface) : iface_(iface) {}
  virtual ~ComposePostServiceIfSingletonFactory() {}

  virtual ComposePostServiceIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(ComposePostServiceIf* /* handler */) {}

 protected:
  ::apache::thrift::stdcxx::shared_ptr<ComposePostServiceIf> iface_;
};

class ComposePostServiceNull : virtual public ComposePostServiceIf {
 public:
  virtual ~ComposePostServiceNull() {}
  void ComposePost(const int64_t /* req_id */, const std::string& /* username */, const int64_t /* user_id */, const std::string& /* text */, const std::vector<int64_t> & /* media_ids */, const std::vector<std::string> & /* media_types */, const PostType::type /* post_type */) {
    return;
  }
  void StorePost(const int64_t /* req_id */, const Post& /* post */) {
    return;
  }
  void ReadPost(Post& /* _return */, const int64_t /* req_id */, const int64_t /* post_id */) {
    return;
  }
  void ReadPosts(std::vector<Post> & /* _return */, const int64_t /* req_id */, const std::vector<int64_t> & /* post_ids */) {
    return;
  }
  void ReadUserTimeline(std::vector<Post> & /* _return */, const int64_t /* req_id */, const int64_t /* user_id */, const int32_t /* start */, const int32_t /* stop */) {
    return;
  }
  void Login(std::string& /* _return */, const int64_t /* req_id */, const std::string& /* username */, const std::string& /* password */) {
    return;
  }
  void RegisterUser(const int64_t /* req_id */, const std::string& /* first_name */, const std::string& /* last_name */, const std::string& /* username */, const std::string& /* password */) {
    return;
  }
  void RegisterUserWithId(const int64_t /* req_id */, const std::string& /* first_name */, const std::string& /* last_name */, const std::string& /* username */, const std::string& /* password */, const int64_t /* user_id */) {
    return;
  }
  void GetFollowers(std::vector<int64_t> & /* _return */, const int64_t /* req_id */, const int64_t /* user_id */) {
    return;
  }
  void Unfollow(const int64_t /* req_id */, const int64_t /* user_id */, const int64_t /* followee_id */) {
    return;
  }
  void UnfollowWithUsername(const int64_t /* req_id */, const std::string& /* user_usernmae */, const std::string& /* followee_username */) {
    return;
  }
  void Follow(const int64_t /* req_id */, const int64_t /* user_id */, const int64_t /* followee_id */) {
    return;
  }
  void FollowWithUsername(const int64_t /* req_id */, const std::string& /* user_usernmae */, const std::string& /* followee_username */) {
    return;
  }
  void GetFollowees(std::vector<int64_t> & /* _return */, const int64_t /* req_id */, const int64_t /* user_id */) {
    return;
  }
  void ReadHomeTimeline(std::vector<Post> & /* _return */, const int64_t /* req_id */, const int64_t /* user_id */, const int32_t /* start */, const int32_t /* stop */) {
    return;
  }
};

typedef struct _ComposePostService_ComposePost_args__isset {
  _ComposePostService_ComposePost_args__isset() : req_id(false), username(false), user_id(false), text(false), media_ids(false), media_types(false), post_type(false) {}
  bool req_id :1;
  bool username :1;
  bool user_id :1;
  bool text :1;
  bool media_ids :1;
  bool media_types :1;
  bool post_type :1;
} _ComposePostService_ComposePost_args__isset;

class ComposePostService_ComposePost_args {
 public:

  ComposePostService_ComposePost_args(const ComposePostService_ComposePost_args&);
  ComposePostService_ComposePost_args& operator=(const ComposePostService_ComposePost_args&);
  ComposePostService_ComposePost_args() : req_id(0), username(), user_id(0), text(), post_type((PostType::type)0) {
  }

  virtual ~ComposePostService_ComposePost_args() throw();
  int64_t req_id;
  std::string username;
  int64_t user_id;
  std::string text;
  std::vector<int64_t>  media_ids;
  std::vector<std::string>  media_types;
  PostType::type post_type;

  _ComposePostService_ComposePost_args__isset __isset;

  void __set_req_id(const int64_t val);

  void __set_username(const std::string& val);

  void __set_user_id(const int64_t val);

  void __set_text(const std::string& val);

  void __set_media_ids(const std::vector<int64_t> & val);

  void __set_media_types(const std::vector<std::string> & val);

  void __set_post_type(const PostType::type val);

  bool operator == (const ComposePostService_ComposePost_args & rhs) const
  {
    if (!(req_id == rhs.req_id))
      return false;
    if (!(username == rhs.username))
      return false;
    if (!(user_id == rhs.user_id))
      return false;
    if (!(text == rhs.text))
      return false;
    if (!(media_ids == rhs.media_ids))
      return false;
    if (!(media_types == rhs.media_types))
      return false;
    if (!(post_type == rhs.post_type))
      return false;
    return true;
  }
  bool operator != (const ComposePostService_ComposePost_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ComposePostService_ComposePost_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class ComposePostService_ComposePost_pargs {
 public:


  virtual ~ComposePostService_ComposePost_pargs() throw();
  const int64_t* req_id;
  const std::string* username;
  const int64_t* user_id;
  const std::string* text;
  const std::vector<int64_t> * media_ids;
  const std::vector<std::string> * media_types;
  const PostType::type* post_type;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ComposePostService_ComposePost_result__isset {
  _ComposePostService_ComposePost_result__isset() : se(false) {}
  bool se :1;
} _ComposePostService_ComposePost_result__isset;

class ComposePostService_ComposePost_result {
 public:

  ComposePostService_ComposePost_result(const ComposePostService_ComposePost_result&);
  ComposePostService_ComposePost_result& operator=(const ComposePostService_ComposePost_result&);
  ComposePostService_ComposePost_result() {
  }

  virtual ~ComposePostService_ComposePost_result() throw();
  ServiceException se;

  _ComposePostService_ComposePost_result__isset __isset;

  void __set_se(const ServiceException& val);

  bool operator == (const ComposePostService_ComposePost_result & rhs) const
  {
    if (!(se == rhs.se))
      return false;
    return true;
  }
  bool operator != (const ComposePostService_ComposePost_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ComposePostService_ComposePost_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ComposePostService_ComposePost_presult__isset {
  _ComposePostService_ComposePost_presult__isset() : se(false) {}
  bool se :1;
} _ComposePostService_ComposePost_presult__isset;

class ComposePostService_ComposePost_presult {
 public:


  virtual ~ComposePostService_ComposePost_presult() throw();
  ServiceException se;

  _ComposePostService_ComposePost_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _ComposePostService_StorePost_args__isset {
  _ComposePostService_StorePost_args__isset() : req_id(false), post(false) {}
  bool req_id :1;
  bool post :1;
} _ComposePostService_StorePost_args__isset;

class ComposePostService_StorePost_args {
 public:

  ComposePostService_StorePost_args(const ComposePostService_StorePost_args&);
  ComposePostService_StorePost_args& operator=(const ComposePostService_StorePost_args&);
  ComposePostService_StorePost_args() : req_id(0) {
  }

  virtual ~ComposePostService_StorePost_args() throw();
  int64_t req_id;
  Post post;

  _ComposePostService_StorePost_args__isset __isset;

  void __set_req_id(const int64_t val);

  void __set_post(const Post& val);

  bool operator == (const ComposePostService_StorePost_args & rhs) const
  {
    if (!(req_id == rhs.req_id))
      return false;
    if (!(post == rhs.post))
      return false;
    return true;
  }
  bool operator != (const ComposePostService_StorePost_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ComposePostService_StorePost_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class ComposePostService_StorePost_pargs {
 public:


  virtual ~ComposePostService_StorePost_pargs() throw();
  const int64_t* req_id;
  const Post* post;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ComposePostService_StorePost_result__isset {
  _ComposePostService_StorePost_result__isset() : se(false) {}
  bool se :1;
} _ComposePostService_StorePost_result__isset;

class ComposePostService_StorePost_result {
 public:

  ComposePostService_StorePost_result(const ComposePostService_StorePost_result&);
  ComposePostService_StorePost_result& operator=(const ComposePostService_StorePost_result&);
  ComposePostService_StorePost_result() {
  }

  virtual ~ComposePostService_StorePost_result() throw();
  ServiceException se;

  _ComposePostService_StorePost_result__isset __isset;

  void __set_se(const ServiceException& val);

  bool operator == (const ComposePostService_StorePost_result & rhs) const
  {
    if (!(se == rhs.se))
      return false;
    return true;
  }
  bool operator != (const ComposePostService_StorePost_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ComposePostService_StorePost_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ComposePostService_StorePost_presult__isset {
  _ComposePostService_StorePost_presult__isset() : se(false) {}
  bool se :1;
} _ComposePostService_StorePost_presult__isset;

class ComposePostService_StorePost_presult {
 public:


  virtual ~ComposePostService_StorePost_presult() throw();
  ServiceException se;

  _ComposePostService_StorePost_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _ComposePostService_ReadPost_args__isset {
  _ComposePostService_ReadPost_args__isset() : req_id(false), post_id(false) {}
  bool req_id :1;
  bool post_id :1;
} _ComposePostService_ReadPost_args__isset;

class ComposePostService_ReadPost_args {
 public:

  ComposePostService_ReadPost_args(const ComposePostService_ReadPost_args&);
  ComposePostService_ReadPost_args& operator=(const ComposePostService_ReadPost_args&);
  ComposePostService_ReadPost_args() : req_id(0), post_id(0) {
  }

  virtual ~ComposePostService_ReadPost_args() throw();
  int64_t req_id;
  int64_t post_id;

  _ComposePostService_ReadPost_args__isset __isset;

  void __set_req_id(const int64_t val);

  void __set_post_id(const int64_t val);

  bool operator == (const ComposePostService_ReadPost_args & rhs) const
  {
    if (!(req_id == rhs.req_id))
      return false;
    if (!(post_id == rhs.post_id))
      return false;
    return true;
  }
  bool operator != (const ComposePostService_ReadPost_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ComposePostService_ReadPost_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class ComposePostService_ReadPost_pargs {
 public:


  virtual ~ComposePostService_ReadPost_pargs() throw();
  const int64_t* req_id;
  const int64_t* post_id;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ComposePostService_ReadPost_result__isset {
  _ComposePostService_ReadPost_result__isset() : success(false), se(false) {}
  bool success :1;
  bool se :1;
} _ComposePostService_ReadPost_result__isset;

class ComposePostService_ReadPost_result {
 public:

  ComposePostService_ReadPost_result(const ComposePostService_ReadPost_result&);
  ComposePostService_ReadPost_result& operator=(const ComposePostService_ReadPost_result&);
  ComposePostService_ReadPost_result() {
  }

  virtual ~ComposePostService_ReadPost_result() throw();
  Post success;
  ServiceException se;

  _ComposePostService_ReadPost_result__isset __isset;

  void __set_success(const Post& val);

  void __set_se(const ServiceException& val);

  bool operator == (const ComposePostService_ReadPost_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    if (!(se == rhs.se))
      return false;
    return true;
  }
  bool operator != (const ComposePostService_ReadPost_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ComposePostService_ReadPost_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ComposePostService_ReadPost_presult__isset {
  _ComposePostService_ReadPost_presult__isset() : success(false), se(false) {}
  bool success :1;
  bool se :1;
} _ComposePostService_ReadPost_presult__isset;

class ComposePostService_ReadPost_presult {
 public:


  virtual ~ComposePostService_ReadPost_presult() throw();
  Post* success;
  ServiceException se;

  _ComposePostService_ReadPost_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _ComposePostService_ReadPosts_args__isset {
  _ComposePostService_ReadPosts_args__isset() : req_id(false), post_ids(false) {}
  bool req_id :1;
  bool post_ids :1;
} _ComposePostService_ReadPosts_args__isset;

class ComposePostService_ReadPosts_args {
 public:

  ComposePostService_ReadPosts_args(const ComposePostService_ReadPosts_args&);
  ComposePostService_ReadPosts_args& operator=(const ComposePostService_ReadPosts_args&);
  ComposePostService_ReadPosts_args() : req_id(0) {
  }

  virtual ~ComposePostService_ReadPosts_args() throw();
  int64_t req_id;
  std::vector<int64_t>  post_ids;

  _ComposePostService_ReadPosts_args__isset __isset;

  void __set_req_id(const int64_t val);

  void __set_post_ids(const std::vector<int64_t> & val);

  bool operator == (const ComposePostService_ReadPosts_args & rhs) const
  {
    if (!(req_id == rhs.req_id))
      return false;
    if (!(post_ids == rhs.post_ids))
      return false;
    return true;
  }
  bool operator != (const ComposePostService_ReadPosts_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ComposePostService_ReadPosts_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class ComposePostService_ReadPosts_pargs {
 public:


  virtual ~ComposePostService_ReadPosts_pargs() throw();
  const int64_t* req_id;
  const std::vector<int64_t> * post_ids;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ComposePostService_ReadPosts_result__isset {
  _ComposePostService_ReadPosts_result__isset() : success(false), se(false) {}
  bool success :1;
  bool se :1;
} _ComposePostService_ReadPosts_result__isset;

class ComposePostService_ReadPosts_result {
 public:

  ComposePostService_ReadPosts_result(const ComposePostService_ReadPosts_result&);
  ComposePostService_ReadPosts_result& operator=(const ComposePostService_ReadPosts_result&);
  ComposePostService_ReadPosts_result() {
  }

  virtual ~ComposePostService_ReadPosts_result() throw();
  std::vector<Post>  success;
  ServiceException se;

  _ComposePostService_ReadPosts_result__isset __isset;

  void __set_success(const std::vector<Post> & val);

  void __set_se(const ServiceException& val);

  bool operator == (const ComposePostService_ReadPosts_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    if (!(se == rhs.se))
      return false;
    return true;
  }
  bool operator != (const ComposePostService_ReadPosts_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ComposePostService_ReadPosts_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ComposePostService_ReadPosts_presult__isset {
  _ComposePostService_ReadPosts_presult__isset() : success(false), se(false) {}
  bool success :1;
  bool se :1;
} _ComposePostService_ReadPosts_presult__isset;

class ComposePostService_ReadPosts_presult {
 public:


  virtual ~ComposePostService_ReadPosts_presult() throw();
  std::vector<Post> * success;
  ServiceException se;

  _ComposePostService_ReadPosts_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _ComposePostService_ReadUserTimeline_args__isset {
  _ComposePostService_ReadUserTimeline_args__isset() : req_id(false), user_id(false), start(false), stop(false) {}
  bool req_id :1;
  bool user_id :1;
  bool start :1;
  bool stop :1;
} _ComposePostService_ReadUserTimeline_args__isset;

class ComposePostService_ReadUserTimeline_args {
 public:

  ComposePostService_ReadUserTimeline_args(const ComposePostService_ReadUserTimeline_args&);
  ComposePostService_ReadUserTimeline_args& operator=(const ComposePostService_ReadUserTimeline_args&);
  ComposePostService_ReadUserTimeline_args() : req_id(0), user_id(0), start(0), stop(0) {
  }

  virtual ~ComposePostService_ReadUserTimeline_args() throw();
  int64_t req_id;
  int64_t user_id;
  int32_t start;
  int32_t stop;

  _ComposePostService_ReadUserTimeline_args__isset __isset;

  void __set_req_id(const int64_t val);

  void __set_user_id(const int64_t val);

  void __set_start(const int32_t val);

  void __set_stop(const int32_t val);

  bool operator == (const ComposePostService_ReadUserTimeline_args & rhs) const
  {
    if (!(req_id == rhs.req_id))
      return false;
    if (!(user_id == rhs.user_id))
      return false;
    if (!(start == rhs.start))
      return false;
    if (!(stop == rhs.stop))
      return false;
    return true;
  }
  bool operator != (const ComposePostService_ReadUserTimeline_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ComposePostService_ReadUserTimeline_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class ComposePostService_ReadUserTimeline_pargs {
 public:


  virtual ~ComposePostService_ReadUserTimeline_pargs() throw();
  const int64_t* req_id;
  const int64_t* user_id;
  const int32_t* start;
  const int32_t* stop;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ComposePostService_ReadUserTimeline_result__isset {
  _ComposePostService_ReadUserTimeline_result__isset() : success(false), se(false) {}
  bool success :1;
  bool se :1;
} _ComposePostService_ReadUserTimeline_result__isset;

class ComposePostService_ReadUserTimeline_result {
 public:

  ComposePostService_ReadUserTimeline_result(const ComposePostService_ReadUserTimeline_result&);
  ComposePostService_ReadUserTimeline_result& operator=(const ComposePostService_ReadUserTimeline_result&);
  ComposePostService_ReadUserTimeline_result() {
  }

  virtual ~ComposePostService_ReadUserTimeline_result() throw();
  std::vector<Post>  success;
  ServiceException se;

  _ComposePostService_ReadUserTimeline_result__isset __isset;

  void __set_success(const std::vector<Post> & val);

  void __set_se(const ServiceException& val);

  bool operator == (const ComposePostService_ReadUserTimeline_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    if (!(se == rhs.se))
      return false;
    return true;
  }
  bool operator != (const ComposePostService_ReadUserTimeline_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ComposePostService_ReadUserTimeline_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ComposePostService_ReadUserTimeline_presult__isset {
  _ComposePostService_ReadUserTimeline_presult__isset() : success(false), se(false) {}
  bool success :1;
  bool se :1;
} _ComposePostService_ReadUserTimeline_presult__isset;

class ComposePostService_ReadUserTimeline_presult {
 public:


  virtual ~ComposePostService_ReadUserTimeline_presult() throw();
  std::vector<Post> * success;
  ServiceException se;

  _ComposePostService_ReadUserTimeline_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _ComposePostService_Login_args__isset {
  _ComposePostService_Login_args__isset() : req_id(false), username(false), password(false) {}
  bool req_id :1;
  bool username :1;
  bool password :1;
} _ComposePostService_Login_args__isset;

class ComposePostService_Login_args {
 public:

  ComposePostService_Login_args(const ComposePostService_Login_args&);
  ComposePostService_Login_args& operator=(const ComposePostService_Login_args&);
  ComposePostService_Login_args() : req_id(0), username(), password() {
  }

  virtual ~ComposePostService_Login_args() throw();
  int64_t req_id;
  std::string username;
  std::string password;

  _ComposePostService_Login_args__isset __isset;

  void __set_req_id(const int64_t val);

  void __set_username(const std::string& val);

  void __set_password(const std::string& val);

  bool operator == (const ComposePostService_Login_args & rhs) const
  {
    if (!(req_id == rhs.req_id))
      return false;
    if (!(username == rhs.username))
      return false;
    if (!(password == rhs.password))
      return false;
    return true;
  }
  bool operator != (const ComposePostService_Login_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ComposePostService_Login_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class ComposePostService_Login_pargs {
 public:


  virtual ~ComposePostService_Login_pargs() throw();
  const int64_t* req_id;
  const std::string* username;
  const std::string* password;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ComposePostService_Login_result__isset {
  _ComposePostService_Login_result__isset() : success(false), se(false) {}
  bool success :1;
  bool se :1;
} _ComposePostService_Login_result__isset;

class ComposePostService_Login_result {
 public:

  ComposePostService_Login_result(const ComposePostService_Login_result&);
  ComposePostService_Login_result& operator=(const ComposePostService_Login_result&);
  ComposePostService_Login_result() : success() {
  }

  virtual ~ComposePostService_Login_result() throw();
  std::string success;
  ServiceException se;

  _ComposePostService_Login_result__isset __isset;

  void __set_success(const std::string& val);

  void __set_se(const ServiceException& val);

  bool operator == (const ComposePostService_Login_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    if (!(se == rhs.se))
      return false;
    return true;
  }
  bool operator != (const ComposePostService_Login_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ComposePostService_Login_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ComposePostService_Login_presult__isset {
  _ComposePostService_Login_presult__isset() : success(false), se(false) {}
  bool success :1;
  bool se :1;
} _ComposePostService_Login_presult__isset;

class ComposePostService_Login_presult {
 public:


  virtual ~ComposePostService_Login_presult() throw();
  std::string* success;
  ServiceException se;

  _ComposePostService_Login_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _ComposePostService_RegisterUser_args__isset {
  _ComposePostService_RegisterUser_args__isset() : req_id(false), first_name(false), last_name(false), username(false), password(false) {}
  bool req_id :1;
  bool first_name :1;
  bool last_name :1;
  bool username :1;
  bool password :1;
} _ComposePostService_RegisterUser_args__isset;

class ComposePostService_RegisterUser_args {
 public:

  ComposePostService_RegisterUser_args(const ComposePostService_RegisterUser_args&);
  ComposePostService_RegisterUser_args& operator=(const ComposePostService_RegisterUser_args&);
  ComposePostService_RegisterUser_args() : req_id(0), first_name(), last_name(), username(), password() {
  }

  virtual ~ComposePostService_RegisterUser_args() throw();
  int64_t req_id;
  std::string first_name;
  std::string last_name;
  std::string username;
  std::string password;

  _ComposePostService_RegisterUser_args__isset __isset;

  void __set_req_id(const int64_t val);

  void __set_first_name(const std::string& val);

  void __set_last_name(const std::string& val);

  void __set_username(const std::string& val);

  void __set_password(const std::string& val);

  bool operator == (const ComposePostService_RegisterUser_args & rhs) const
  {
    if (!(req_id == rhs.req_id))
      return false;
    if (!(first_name == rhs.first_name))
      return false;
    if (!(last_name == rhs.last_name))
      return false;
    if (!(username == rhs.username))
      return false;
    if (!(password == rhs.password))
      return false;
    return true;
  }
  bool operator != (const ComposePostService_RegisterUser_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ComposePostService_RegisterUser_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class ComposePostService_RegisterUser_pargs {
 public:


  virtual ~ComposePostService_RegisterUser_pargs() throw();
  const int64_t* req_id;
  const std::string* first_name;
  const std::string* last_name;
  const std::string* username;
  const std::string* password;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ComposePostService_RegisterUser_result__isset {
  _ComposePostService_RegisterUser_result__isset() : se(false) {}
  bool se :1;
} _ComposePostService_RegisterUser_result__isset;

class ComposePostService_RegisterUser_result {
 public:

  ComposePostService_RegisterUser_result(const ComposePostService_RegisterUser_result&);
  ComposePostService_RegisterUser_result& operator=(const ComposePostService_RegisterUser_result&);
  ComposePostService_RegisterUser_result() {
  }

  virtual ~ComposePostService_RegisterUser_result() throw();
  ServiceException se;

  _ComposePostService_RegisterUser_result__isset __isset;

  void __set_se(const ServiceException& val);

  bool operator == (const ComposePostService_RegisterUser_result & rhs) const
  {
    if (!(se == rhs.se))
      return false;
    return true;
  }
  bool operator != (const ComposePostService_RegisterUser_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ComposePostService_RegisterUser_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ComposePostService_RegisterUser_presult__isset {
  _ComposePostService_RegisterUser_presult__isset() : se(false) {}
  bool se :1;
} _ComposePostService_RegisterUser_presult__isset;

class ComposePostService_RegisterUser_presult {
 public:


  virtual ~ComposePostService_RegisterUser_presult() throw();
  ServiceException se;

  _ComposePostService_RegisterUser_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _ComposePostService_RegisterUserWithId_args__isset {
  _ComposePostService_RegisterUserWithId_args__isset() : req_id(false), first_name(false), last_name(false), username(false), password(false), user_id(false) {}
  bool req_id :1;
  bool first_name :1;
  bool last_name :1;
  bool username :1;
  bool password :1;
  bool user_id :1;
} _ComposePostService_RegisterUserWithId_args__isset;

class ComposePostService_RegisterUserWithId_args {
 public:

  ComposePostService_RegisterUserWithId_args(const ComposePostService_RegisterUserWithId_args&);
  ComposePostService_RegisterUserWithId_args& operator=(const ComposePostService_RegisterUserWithId_args&);
  ComposePostService_RegisterUserWithId_args() : req_id(0), first_name(), last_name(), username(), password(), user_id(0) {
  }

  virtual ~ComposePostService_RegisterUserWithId_args() throw();
  int64_t req_id;
  std::string first_name;
  std::string last_name;
  std::string username;
  std::string password;
  int64_t user_id;

  _ComposePostService_RegisterUserWithId_args__isset __isset;

  void __set_req_id(const int64_t val);

  void __set_first_name(const std::string& val);

  void __set_last_name(const std::string& val);

  void __set_username(const std::string& val);

  void __set_password(const std::string& val);

  void __set_user_id(const int64_t val);

  bool operator == (const ComposePostService_RegisterUserWithId_args & rhs) const
  {
    if (!(req_id == rhs.req_id))
      return false;
    if (!(first_name == rhs.first_name))
      return false;
    if (!(last_name == rhs.last_name))
      return false;
    if (!(username == rhs.username))
      return false;
    if (!(password == rhs.password))
      return false;
    if (!(user_id == rhs.user_id))
      return false;
    return true;
  }
  bool operator != (const ComposePostService_RegisterUserWithId_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ComposePostService_RegisterUserWithId_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class ComposePostService_RegisterUserWithId_pargs {
 public:


  virtual ~ComposePostService_RegisterUserWithId_pargs() throw();
  const int64_t* req_id;
  const std::string* first_name;
  const std::string* last_name;
  const std::string* username;
  const std::string* password;
  const int64_t* user_id;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ComposePostService_RegisterUserWithId_result__isset {
  _ComposePostService_RegisterUserWithId_result__isset() : se(false) {}
  bool se :1;
} _ComposePostService_RegisterUserWithId_result__isset;

class ComposePostService_RegisterUserWithId_result {
 public:

  ComposePostService_RegisterUserWithId_result(const ComposePostService_RegisterUserWithId_result&);
  ComposePostService_RegisterUserWithId_result& operator=(const ComposePostService_RegisterUserWithId_result&);
  ComposePostService_RegisterUserWithId_result() {
  }

  virtual ~ComposePostService_RegisterUserWithId_result() throw();
  ServiceException se;

  _ComposePostService_RegisterUserWithId_result__isset __isset;

  void __set_se(const ServiceException& val);

  bool operator == (const ComposePostService_RegisterUserWithId_result & rhs) const
  {
    if (!(se == rhs.se))
      return false;
    return true;
  }
  bool operator != (const ComposePostService_RegisterUserWithId_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ComposePostService_RegisterUserWithId_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ComposePostService_RegisterUserWithId_presult__isset {
  _ComposePostService_RegisterUserWithId_presult__isset() : se(false) {}
  bool se :1;
} _ComposePostService_RegisterUserWithId_presult__isset;

class ComposePostService_RegisterUserWithId_presult {
 public:


  virtual ~ComposePostService_RegisterUserWithId_presult() throw();
  ServiceException se;

  _ComposePostService_RegisterUserWithId_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _ComposePostService_GetFollowers_args__isset {
  _ComposePostService_GetFollowers_args__isset() : req_id(false), user_id(false) {}
  bool req_id :1;
  bool user_id :1;
} _ComposePostService_GetFollowers_args__isset;

class ComposePostService_GetFollowers_args {
 public:

  ComposePostService_GetFollowers_args(const ComposePostService_GetFollowers_args&);
  ComposePostService_GetFollowers_args& operator=(const ComposePostService_GetFollowers_args&);
  ComposePostService_GetFollowers_args() : req_id(0), user_id(0) {
  }

  virtual ~ComposePostService_GetFollowers_args() throw();
  int64_t req_id;
  int64_t user_id;

  _ComposePostService_GetFollowers_args__isset __isset;

  void __set_req_id(const int64_t val);

  void __set_user_id(const int64_t val);

  bool operator == (const ComposePostService_GetFollowers_args & rhs) const
  {
    if (!(req_id == rhs.req_id))
      return false;
    if (!(user_id == rhs.user_id))
      return false;
    return true;
  }
  bool operator != (const ComposePostService_GetFollowers_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ComposePostService_GetFollowers_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class ComposePostService_GetFollowers_pargs {
 public:


  virtual ~ComposePostService_GetFollowers_pargs() throw();
  const int64_t* req_id;
  const int64_t* user_id;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ComposePostService_GetFollowers_result__isset {
  _ComposePostService_GetFollowers_result__isset() : success(false), se(false) {}
  bool success :1;
  bool se :1;
} _ComposePostService_GetFollowers_result__isset;

class ComposePostService_GetFollowers_result {
 public:

  ComposePostService_GetFollowers_result(const ComposePostService_GetFollowers_result&);
  ComposePostService_GetFollowers_result& operator=(const ComposePostService_GetFollowers_result&);
  ComposePostService_GetFollowers_result() {
  }

  virtual ~ComposePostService_GetFollowers_result() throw();
  std::vector<int64_t>  success;
  ServiceException se;

  _ComposePostService_GetFollowers_result__isset __isset;

  void __set_success(const std::vector<int64_t> & val);

  void __set_se(const ServiceException& val);

  bool operator == (const ComposePostService_GetFollowers_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    if (!(se == rhs.se))
      return false;
    return true;
  }
  bool operator != (const ComposePostService_GetFollowers_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ComposePostService_GetFollowers_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ComposePostService_GetFollowers_presult__isset {
  _ComposePostService_GetFollowers_presult__isset() : success(false), se(false) {}
  bool success :1;
  bool se :1;
} _ComposePostService_GetFollowers_presult__isset;

class ComposePostService_GetFollowers_presult {
 public:


  virtual ~ComposePostService_GetFollowers_presult() throw();
  std::vector<int64_t> * success;
  ServiceException se;

  _ComposePostService_GetFollowers_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _ComposePostService_Unfollow_args__isset {
  _ComposePostService_Unfollow_args__isset() : req_id(false), user_id(false), followee_id(false) {}
  bool req_id :1;
  bool user_id :1;
  bool followee_id :1;
} _ComposePostService_Unfollow_args__isset;

class ComposePostService_Unfollow_args {
 public:

  ComposePostService_Unfollow_args(const ComposePostService_Unfollow_args&);
  ComposePostService_Unfollow_args& operator=(const ComposePostService_Unfollow_args&);
  ComposePostService_Unfollow_args() : req_id(0), user_id(0), followee_id(0) {
  }

  virtual ~ComposePostService_Unfollow_args() throw();
  int64_t req_id;
  int64_t user_id;
  int64_t followee_id;

  _ComposePostService_Unfollow_args__isset __isset;

  void __set_req_id(const int64_t val);

  void __set_user_id(const int64_t val);

  void __set_followee_id(const int64_t val);

  bool operator == (const ComposePostService_Unfollow_args & rhs) const
  {
    if (!(req_id == rhs.req_id))
      return false;
    if (!(user_id == rhs.user_id))
      return false;
    if (!(followee_id == rhs.followee_id))
      return false;
    return true;
  }
  bool operator != (const ComposePostService_Unfollow_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ComposePostService_Unfollow_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class ComposePostService_Unfollow_pargs {
 public:


  virtual ~ComposePostService_Unfollow_pargs() throw();
  const int64_t* req_id;
  const int64_t* user_id;
  const int64_t* followee_id;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ComposePostService_Unfollow_result__isset {
  _ComposePostService_Unfollow_result__isset() : se(false) {}
  bool se :1;
} _ComposePostService_Unfollow_result__isset;

class ComposePostService_Unfollow_result {
 public:

  ComposePostService_Unfollow_result(const ComposePostService_Unfollow_result&);
  ComposePostService_Unfollow_result& operator=(const ComposePostService_Unfollow_result&);
  ComposePostService_Unfollow_result() {
  }

  virtual ~ComposePostService_Unfollow_result() throw();
  ServiceException se;

  _ComposePostService_Unfollow_result__isset __isset;

  void __set_se(const ServiceException& val);

  bool operator == (const ComposePostService_Unfollow_result & rhs) const
  {
    if (!(se == rhs.se))
      return false;
    return true;
  }
  bool operator != (const ComposePostService_Unfollow_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ComposePostService_Unfollow_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ComposePostService_Unfollow_presult__isset {
  _ComposePostService_Unfollow_presult__isset() : se(false) {}
  bool se :1;
} _ComposePostService_Unfollow_presult__isset;

class ComposePostService_Unfollow_presult {
 public:


  virtual ~ComposePostService_Unfollow_presult() throw();
  ServiceException se;

  _ComposePostService_Unfollow_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _ComposePostService_UnfollowWithUsername_args__isset {
  _ComposePostService_UnfollowWithUsername_args__isset() : req_id(false), user_usernmae(false), followee_username(false) {}
  bool req_id :1;
  bool user_usernmae :1;
  bool followee_username :1;
} _ComposePostService_UnfollowWithUsername_args__isset;

class ComposePostService_UnfollowWithUsername_args {
 public:

  ComposePostService_UnfollowWithUsername_args(const ComposePostService_UnfollowWithUsername_args&);
  ComposePostService_UnfollowWithUsername_args& operator=(const ComposePostService_UnfollowWithUsername_args&);
  ComposePostService_UnfollowWithUsername_args() : req_id(0), user_usernmae(), followee_username() {
  }

  virtual ~ComposePostService_UnfollowWithUsername_args() throw();
  int64_t req_id;
  std::string user_usernmae;
  std::string followee_username;

  _ComposePostService_UnfollowWithUsername_args__isset __isset;

  void __set_req_id(const int64_t val);

  void __set_user_usernmae(const std::string& val);

  void __set_followee_username(const std::string& val);

  bool operator == (const ComposePostService_UnfollowWithUsername_args & rhs) const
  {
    if (!(req_id == rhs.req_id))
      return false;
    if (!(user_usernmae == rhs.user_usernmae))
      return false;
    if (!(followee_username == rhs.followee_username))
      return false;
    return true;
  }
  bool operator != (const ComposePostService_UnfollowWithUsername_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ComposePostService_UnfollowWithUsername_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class ComposePostService_UnfollowWithUsername_pargs {
 public:


  virtual ~ComposePostService_UnfollowWithUsername_pargs() throw();
  const int64_t* req_id;
  const std::string* user_usernmae;
  const std::string* followee_username;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ComposePostService_UnfollowWithUsername_result__isset {
  _ComposePostService_UnfollowWithUsername_result__isset() : se(false) {}
  bool se :1;
} _ComposePostService_UnfollowWithUsername_result__isset;

class ComposePostService_UnfollowWithUsername_result {
 public:

  ComposePostService_UnfollowWithUsername_result(const ComposePostService_UnfollowWithUsername_result&);
  ComposePostService_UnfollowWithUsername_result& operator=(const ComposePostService_UnfollowWithUsername_result&);
  ComposePostService_UnfollowWithUsername_result() {
  }

  virtual ~ComposePostService_UnfollowWithUsername_result() throw();
  ServiceException se;

  _ComposePostService_UnfollowWithUsername_result__isset __isset;

  void __set_se(const ServiceException& val);

  bool operator == (const ComposePostService_UnfollowWithUsername_result & rhs) const
  {
    if (!(se == rhs.se))
      return false;
    return true;
  }
  bool operator != (const ComposePostService_UnfollowWithUsername_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ComposePostService_UnfollowWithUsername_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ComposePostService_UnfollowWithUsername_presult__isset {
  _ComposePostService_UnfollowWithUsername_presult__isset() : se(false) {}
  bool se :1;
} _ComposePostService_UnfollowWithUsername_presult__isset;

class ComposePostService_UnfollowWithUsername_presult {
 public:


  virtual ~ComposePostService_UnfollowWithUsername_presult() throw();
  ServiceException se;

  _ComposePostService_UnfollowWithUsername_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _ComposePostService_Follow_args__isset {
  _ComposePostService_Follow_args__isset() : req_id(false), user_id(false), followee_id(false) {}
  bool req_id :1;
  bool user_id :1;
  bool followee_id :1;
} _ComposePostService_Follow_args__isset;

class ComposePostService_Follow_args {
 public:

  ComposePostService_Follow_args(const ComposePostService_Follow_args&);
  ComposePostService_Follow_args& operator=(const ComposePostService_Follow_args&);
  ComposePostService_Follow_args() : req_id(0), user_id(0), followee_id(0) {
  }

  virtual ~ComposePostService_Follow_args() throw();
  int64_t req_id;
  int64_t user_id;
  int64_t followee_id;

  _ComposePostService_Follow_args__isset __isset;

  void __set_req_id(const int64_t val);

  void __set_user_id(const int64_t val);

  void __set_followee_id(const int64_t val);

  bool operator == (const ComposePostService_Follow_args & rhs) const
  {
    if (!(req_id == rhs.req_id))
      return false;
    if (!(user_id == rhs.user_id))
      return false;
    if (!(followee_id == rhs.followee_id))
      return false;
    return true;
  }
  bool operator != (const ComposePostService_Follow_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ComposePostService_Follow_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class ComposePostService_Follow_pargs {
 public:


  virtual ~ComposePostService_Follow_pargs() throw();
  const int64_t* req_id;
  const int64_t* user_id;
  const int64_t* followee_id;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ComposePostService_Follow_result__isset {
  _ComposePostService_Follow_result__isset() : se(false) {}
  bool se :1;
} _ComposePostService_Follow_result__isset;

class ComposePostService_Follow_result {
 public:

  ComposePostService_Follow_result(const ComposePostService_Follow_result&);
  ComposePostService_Follow_result& operator=(const ComposePostService_Follow_result&);
  ComposePostService_Follow_result() {
  }

  virtual ~ComposePostService_Follow_result() throw();
  ServiceException se;

  _ComposePostService_Follow_result__isset __isset;

  void __set_se(const ServiceException& val);

  bool operator == (const ComposePostService_Follow_result & rhs) const
  {
    if (!(se == rhs.se))
      return false;
    return true;
  }
  bool operator != (const ComposePostService_Follow_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ComposePostService_Follow_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ComposePostService_Follow_presult__isset {
  _ComposePostService_Follow_presult__isset() : se(false) {}
  bool se :1;
} _ComposePostService_Follow_presult__isset;

class ComposePostService_Follow_presult {
 public:


  virtual ~ComposePostService_Follow_presult() throw();
  ServiceException se;

  _ComposePostService_Follow_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _ComposePostService_FollowWithUsername_args__isset {
  _ComposePostService_FollowWithUsername_args__isset() : req_id(false), user_usernmae(false), followee_username(false) {}
  bool req_id :1;
  bool user_usernmae :1;
  bool followee_username :1;
} _ComposePostService_FollowWithUsername_args__isset;

class ComposePostService_FollowWithUsername_args {
 public:

  ComposePostService_FollowWithUsername_args(const ComposePostService_FollowWithUsername_args&);
  ComposePostService_FollowWithUsername_args& operator=(const ComposePostService_FollowWithUsername_args&);
  ComposePostService_FollowWithUsername_args() : req_id(0), user_usernmae(), followee_username() {
  }

  virtual ~ComposePostService_FollowWithUsername_args() throw();
  int64_t req_id;
  std::string user_usernmae;
  std::string followee_username;

  _ComposePostService_FollowWithUsername_args__isset __isset;

  void __set_req_id(const int64_t val);

  void __set_user_usernmae(const std::string& val);

  void __set_followee_username(const std::string& val);

  bool operator == (const ComposePostService_FollowWithUsername_args & rhs) const
  {
    if (!(req_id == rhs.req_id))
      return false;
    if (!(user_usernmae == rhs.user_usernmae))
      return false;
    if (!(followee_username == rhs.followee_username))
      return false;
    return true;
  }
  bool operator != (const ComposePostService_FollowWithUsername_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ComposePostService_FollowWithUsername_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class ComposePostService_FollowWithUsername_pargs {
 public:


  virtual ~ComposePostService_FollowWithUsername_pargs() throw();
  const int64_t* req_id;
  const std::string* user_usernmae;
  const std::string* followee_username;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ComposePostService_FollowWithUsername_result__isset {
  _ComposePostService_FollowWithUsername_result__isset() : se(false) {}
  bool se :1;
} _ComposePostService_FollowWithUsername_result__isset;

class ComposePostService_FollowWithUsername_result {
 public:

  ComposePostService_FollowWithUsername_result(const ComposePostService_FollowWithUsername_result&);
  ComposePostService_FollowWithUsername_result& operator=(const ComposePostService_FollowWithUsername_result&);
  ComposePostService_FollowWithUsername_result() {
  }

  virtual ~ComposePostService_FollowWithUsername_result() throw();
  ServiceException se;

  _ComposePostService_FollowWithUsername_result__isset __isset;

  void __set_se(const ServiceException& val);

  bool operator == (const ComposePostService_FollowWithUsername_result & rhs) const
  {
    if (!(se == rhs.se))
      return false;
    return true;
  }
  bool operator != (const ComposePostService_FollowWithUsername_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ComposePostService_FollowWithUsername_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ComposePostService_FollowWithUsername_presult__isset {
  _ComposePostService_FollowWithUsername_presult__isset() : se(false) {}
  bool se :1;
} _ComposePostService_FollowWithUsername_presult__isset;

class ComposePostService_FollowWithUsername_presult {
 public:


  virtual ~ComposePostService_FollowWithUsername_presult() throw();
  ServiceException se;

  _ComposePostService_FollowWithUsername_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _ComposePostService_GetFollowees_args__isset {
  _ComposePostService_GetFollowees_args__isset() : req_id(false), user_id(false) {}
  bool req_id :1;
  bool user_id :1;
} _ComposePostService_GetFollowees_args__isset;

class ComposePostService_GetFollowees_args {
 public:

  ComposePostService_GetFollowees_args(const ComposePostService_GetFollowees_args&);
  ComposePostService_GetFollowees_args& operator=(const ComposePostService_GetFollowees_args&);
  ComposePostService_GetFollowees_args() : req_id(0), user_id(0) {
  }

  virtual ~ComposePostService_GetFollowees_args() throw();
  int64_t req_id;
  int64_t user_id;

  _ComposePostService_GetFollowees_args__isset __isset;

  void __set_req_id(const int64_t val);

  void __set_user_id(const int64_t val);

  bool operator == (const ComposePostService_GetFollowees_args & rhs) const
  {
    if (!(req_id == rhs.req_id))
      return false;
    if (!(user_id == rhs.user_id))
      return false;
    return true;
  }
  bool operator != (const ComposePostService_GetFollowees_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ComposePostService_GetFollowees_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class ComposePostService_GetFollowees_pargs {
 public:


  virtual ~ComposePostService_GetFollowees_pargs() throw();
  const int64_t* req_id;
  const int64_t* user_id;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ComposePostService_GetFollowees_result__isset {
  _ComposePostService_GetFollowees_result__isset() : success(false), se(false) {}
  bool success :1;
  bool se :1;
} _ComposePostService_GetFollowees_result__isset;

class ComposePostService_GetFollowees_result {
 public:

  ComposePostService_GetFollowees_result(const ComposePostService_GetFollowees_result&);
  ComposePostService_GetFollowees_result& operator=(const ComposePostService_GetFollowees_result&);
  ComposePostService_GetFollowees_result() {
  }

  virtual ~ComposePostService_GetFollowees_result() throw();
  std::vector<int64_t>  success;
  ServiceException se;

  _ComposePostService_GetFollowees_result__isset __isset;

  void __set_success(const std::vector<int64_t> & val);

  void __set_se(const ServiceException& val);

  bool operator == (const ComposePostService_GetFollowees_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    if (!(se == rhs.se))
      return false;
    return true;
  }
  bool operator != (const ComposePostService_GetFollowees_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ComposePostService_GetFollowees_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ComposePostService_GetFollowees_presult__isset {
  _ComposePostService_GetFollowees_presult__isset() : success(false), se(false) {}
  bool success :1;
  bool se :1;
} _ComposePostService_GetFollowees_presult__isset;

class ComposePostService_GetFollowees_presult {
 public:


  virtual ~ComposePostService_GetFollowees_presult() throw();
  std::vector<int64_t> * success;
  ServiceException se;

  _ComposePostService_GetFollowees_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _ComposePostService_ReadHomeTimeline_args__isset {
  _ComposePostService_ReadHomeTimeline_args__isset() : req_id(false), user_id(false), start(false), stop(false) {}
  bool req_id :1;
  bool user_id :1;
  bool start :1;
  bool stop :1;
} _ComposePostService_ReadHomeTimeline_args__isset;

class ComposePostService_ReadHomeTimeline_args {
 public:

  ComposePostService_ReadHomeTimeline_args(const ComposePostService_ReadHomeTimeline_args&);
  ComposePostService_ReadHomeTimeline_args& operator=(const ComposePostService_ReadHomeTimeline_args&);
  ComposePostService_ReadHomeTimeline_args() : req_id(0), user_id(0), start(0), stop(0) {
  }

  virtual ~ComposePostService_ReadHomeTimeline_args() throw();
  int64_t req_id;
  int64_t user_id;
  int32_t start;
  int32_t stop;

  _ComposePostService_ReadHomeTimeline_args__isset __isset;

  void __set_req_id(const int64_t val);

  void __set_user_id(const int64_t val);

  void __set_start(const int32_t val);

  void __set_stop(const int32_t val);

  bool operator == (const ComposePostService_ReadHomeTimeline_args & rhs) const
  {
    if (!(req_id == rhs.req_id))
      return false;
    if (!(user_id == rhs.user_id))
      return false;
    if (!(start == rhs.start))
      return false;
    if (!(stop == rhs.stop))
      return false;
    return true;
  }
  bool operator != (const ComposePostService_ReadHomeTimeline_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ComposePostService_ReadHomeTimeline_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class ComposePostService_ReadHomeTimeline_pargs {
 public:


  virtual ~ComposePostService_ReadHomeTimeline_pargs() throw();
  const int64_t* req_id;
  const int64_t* user_id;
  const int32_t* start;
  const int32_t* stop;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ComposePostService_ReadHomeTimeline_result__isset {
  _ComposePostService_ReadHomeTimeline_result__isset() : success(false), se(false) {}
  bool success :1;
  bool se :1;
} _ComposePostService_ReadHomeTimeline_result__isset;

class ComposePostService_ReadHomeTimeline_result {
 public:

  ComposePostService_ReadHomeTimeline_result(const ComposePostService_ReadHomeTimeline_result&);
  ComposePostService_ReadHomeTimeline_result& operator=(const ComposePostService_ReadHomeTimeline_result&);
  ComposePostService_ReadHomeTimeline_result() {
  }

  virtual ~ComposePostService_ReadHomeTimeline_result() throw();
  std::vector<Post>  success;
  ServiceException se;

  _ComposePostService_ReadHomeTimeline_result__isset __isset;

  void __set_success(const std::vector<Post> & val);

  void __set_se(const ServiceException& val);

  bool operator == (const ComposePostService_ReadHomeTimeline_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    if (!(se == rhs.se))
      return false;
    return true;
  }
  bool operator != (const ComposePostService_ReadHomeTimeline_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ComposePostService_ReadHomeTimeline_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ComposePostService_ReadHomeTimeline_presult__isset {
  _ComposePostService_ReadHomeTimeline_presult__isset() : success(false), se(false) {}
  bool success :1;
  bool se :1;
} _ComposePostService_ReadHomeTimeline_presult__isset;

class ComposePostService_ReadHomeTimeline_presult {
 public:


  virtual ~ComposePostService_ReadHomeTimeline_presult() throw();
  std::vector<Post> * success;
  ServiceException se;

  _ComposePostService_ReadHomeTimeline_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class ComposePostServiceClient : virtual public ComposePostServiceIf {
 public:
  ComposePostServiceClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  ComposePostServiceClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void ComposePost(const int64_t req_id, const std::string& username, const int64_t user_id, const std::string& text, const std::vector<int64_t> & media_ids, const std::vector<std::string> & media_types, const PostType::type post_type);
  void send_ComposePost(const int64_t req_id, const std::string& username, const int64_t user_id, const std::string& text, const std::vector<int64_t> & media_ids, const std::vector<std::string> & media_types, const PostType::type post_type);
  void recv_ComposePost();
  void StorePost(const int64_t req_id, const Post& post);
  void send_StorePost(const int64_t req_id, const Post& post);
  void recv_StorePost();
  void ReadPost(Post& _return, const int64_t req_id, const int64_t post_id);
  void send_ReadPost(const int64_t req_id, const int64_t post_id);
  void recv_ReadPost(Post& _return);
  void ReadPosts(std::vector<Post> & _return, const int64_t req_id, const std::vector<int64_t> & post_ids);
  void send_ReadPosts(const int64_t req_id, const std::vector<int64_t> & post_ids);
  void recv_ReadPosts(std::vector<Post> & _return);
  void ReadUserTimeline(std::vector<Post> & _return, const int64_t req_id, const int64_t user_id, const int32_t start, const int32_t stop);
  void send_ReadUserTimeline(const int64_t req_id, const int64_t user_id, const int32_t start, const int32_t stop);
  void recv_ReadUserTimeline(std::vector<Post> & _return);
  void Login(std::string& _return, const int64_t req_id, const std::string& username, const std::string& password);
  void send_Login(const int64_t req_id, const std::string& username, const std::string& password);
  void recv_Login(std::string& _return);
  void RegisterUser(const int64_t req_id, const std::string& first_name, const std::string& last_name, const std::string& username, const std::string& password);
  void send_RegisterUser(const int64_t req_id, const std::string& first_name, const std::string& last_name, const std::string& username, const std::string& password);
  void recv_RegisterUser();
  void RegisterUserWithId(const int64_t req_id, const std::string& first_name, const std::string& last_name, const std::string& username, const std::string& password, const int64_t user_id);
  void send_RegisterUserWithId(const int64_t req_id, const std::string& first_name, const std::string& last_name, const std::string& username, const std::string& password, const int64_t user_id);
  void recv_RegisterUserWithId();
  void GetFollowers(std::vector<int64_t> & _return, const int64_t req_id, const int64_t user_id);
  void send_GetFollowers(const int64_t req_id, const int64_t user_id);
  void recv_GetFollowers(std::vector<int64_t> & _return);
  void Unfollow(const int64_t req_id, const int64_t user_id, const int64_t followee_id);
  void send_Unfollow(const int64_t req_id, const int64_t user_id, const int64_t followee_id);
  void recv_Unfollow();
  void UnfollowWithUsername(const int64_t req_id, const std::string& user_usernmae, const std::string& followee_username);
  void send_UnfollowWithUsername(const int64_t req_id, const std::string& user_usernmae, const std::string& followee_username);
  void recv_UnfollowWithUsername();
  void Follow(const int64_t req_id, const int64_t user_id, const int64_t followee_id);
  void send_Follow(const int64_t req_id, const int64_t user_id, const int64_t followee_id);
  void recv_Follow();
  void FollowWithUsername(const int64_t req_id, const std::string& user_usernmae, const std::string& followee_username);
  void send_FollowWithUsername(const int64_t req_id, const std::string& user_usernmae, const std::string& followee_username);
  void recv_FollowWithUsername();
  void GetFollowees(std::vector<int64_t> & _return, const int64_t req_id, const int64_t user_id);
  void send_GetFollowees(const int64_t req_id, const int64_t user_id);
  void recv_GetFollowees(std::vector<int64_t> & _return);
  void ReadHomeTimeline(std::vector<Post> & _return, const int64_t req_id, const int64_t user_id, const int32_t start, const int32_t stop);
  void send_ReadHomeTimeline(const int64_t req_id, const int64_t user_id, const int32_t start, const int32_t stop);
  void recv_ReadHomeTimeline(std::vector<Post> & _return);
 protected:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class ComposePostServiceProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  ::apache::thrift::stdcxx::shared_ptr<ComposePostServiceIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (ComposePostServiceProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_ComposePost(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_StorePost(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_ReadPost(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_ReadPosts(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_ReadUserTimeline(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_Login(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_RegisterUser(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_RegisterUserWithId(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_GetFollowers(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_Unfollow(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_UnfollowWithUsername(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_Follow(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_FollowWithUsername(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_GetFollowees(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_ReadHomeTimeline(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  ComposePostServiceProcessor(::apache::thrift::stdcxx::shared_ptr<ComposePostServiceIf> iface) :
    iface_(iface) {
    processMap_["ComposePost"] = &ComposePostServiceProcessor::process_ComposePost;
    processMap_["StorePost"] = &ComposePostServiceProcessor::process_StorePost;
    processMap_["ReadPost"] = &ComposePostServiceProcessor::process_ReadPost;
    processMap_["ReadPosts"] = &ComposePostServiceProcessor::process_ReadPosts;
    processMap_["ReadUserTimeline"] = &ComposePostServiceProcessor::process_ReadUserTimeline;
    processMap_["Login"] = &ComposePostServiceProcessor::process_Login;
    processMap_["RegisterUser"] = &ComposePostServiceProcessor::process_RegisterUser;
    processMap_["RegisterUserWithId"] = &ComposePostServiceProcessor::process_RegisterUserWithId;
    processMap_["GetFollowers"] = &ComposePostServiceProcessor::process_GetFollowers;
    processMap_["Unfollow"] = &ComposePostServiceProcessor::process_Unfollow;
    processMap_["UnfollowWithUsername"] = &ComposePostServiceProcessor::process_UnfollowWithUsername;
    processMap_["Follow"] = &ComposePostServiceProcessor::process_Follow;
    processMap_["FollowWithUsername"] = &ComposePostServiceProcessor::process_FollowWithUsername;
    processMap_["GetFollowees"] = &ComposePostServiceProcessor::process_GetFollowees;
    processMap_["ReadHomeTimeline"] = &ComposePostServiceProcessor::process_ReadHomeTimeline;
  }

  virtual ~ComposePostServiceProcessor() {}
};

class ComposePostServiceProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  ComposePostServiceProcessorFactory(const ::apache::thrift::stdcxx::shared_ptr< ComposePostServiceIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::apache::thrift::stdcxx::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::apache::thrift::stdcxx::shared_ptr< ComposePostServiceIfFactory > handlerFactory_;
};

class ComposePostServiceMultiface : virtual public ComposePostServiceIf {
 public:
  ComposePostServiceMultiface(std::vector<apache::thrift::stdcxx::shared_ptr<ComposePostServiceIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~ComposePostServiceMultiface() {}
 protected:
  std::vector<apache::thrift::stdcxx::shared_ptr<ComposePostServiceIf> > ifaces_;
  ComposePostServiceMultiface() {}
  void add(::apache::thrift::stdcxx::shared_ptr<ComposePostServiceIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void ComposePost(const int64_t req_id, const std::string& username, const int64_t user_id, const std::string& text, const std::vector<int64_t> & media_ids, const std::vector<std::string> & media_types, const PostType::type post_type) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->ComposePost(req_id, username, user_id, text, media_ids, media_types, post_type);
    }
    ifaces_[i]->ComposePost(req_id, username, user_id, text, media_ids, media_types, post_type);
  }

  void StorePost(const int64_t req_id, const Post& post) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->StorePost(req_id, post);
    }
    ifaces_[i]->StorePost(req_id, post);
  }

  void ReadPost(Post& _return, const int64_t req_id, const int64_t post_id) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->ReadPost(_return, req_id, post_id);
    }
    ifaces_[i]->ReadPost(_return, req_id, post_id);
    return;
  }

  void ReadPosts(std::vector<Post> & _return, const int64_t req_id, const std::vector<int64_t> & post_ids) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->ReadPosts(_return, req_id, post_ids);
    }
    ifaces_[i]->ReadPosts(_return, req_id, post_ids);
    return;
  }

  void ReadUserTimeline(std::vector<Post> & _return, const int64_t req_id, const int64_t user_id, const int32_t start, const int32_t stop) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->ReadUserTimeline(_return, req_id, user_id, start, stop);
    }
    ifaces_[i]->ReadUserTimeline(_return, req_id, user_id, start, stop);
    return;
  }

  void Login(std::string& _return, const int64_t req_id, const std::string& username, const std::string& password) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->Login(_return, req_id, username, password);
    }
    ifaces_[i]->Login(_return, req_id, username, password);
    return;
  }

  void RegisterUser(const int64_t req_id, const std::string& first_name, const std::string& last_name, const std::string& username, const std::string& password) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->RegisterUser(req_id, first_name, last_name, username, password);
    }
    ifaces_[i]->RegisterUser(req_id, first_name, last_name, username, password);
  }

  void RegisterUserWithId(const int64_t req_id, const std::string& first_name, const std::string& last_name, const std::string& username, const std::string& password, const int64_t user_id) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->RegisterUserWithId(req_id, first_name, last_name, username, password, user_id);
    }
    ifaces_[i]->RegisterUserWithId(req_id, first_name, last_name, username, password, user_id);
  }

  void GetFollowers(std::vector<int64_t> & _return, const int64_t req_id, const int64_t user_id) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->GetFollowers(_return, req_id, user_id);
    }
    ifaces_[i]->GetFollowers(_return, req_id, user_id);
    return;
  }

  void Unfollow(const int64_t req_id, const int64_t user_id, const int64_t followee_id) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->Unfollow(req_id, user_id, followee_id);
    }
    ifaces_[i]->Unfollow(req_id, user_id, followee_id);
  }

  void UnfollowWithUsername(const int64_t req_id, const std::string& user_usernmae, const std::string& followee_username) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->UnfollowWithUsername(req_id, user_usernmae, followee_username);
    }
    ifaces_[i]->UnfollowWithUsername(req_id, user_usernmae, followee_username);
  }

  void Follow(const int64_t req_id, const int64_t user_id, const int64_t followee_id) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->Follow(req_id, user_id, followee_id);
    }
    ifaces_[i]->Follow(req_id, user_id, followee_id);
  }

  void FollowWithUsername(const int64_t req_id, const std::string& user_usernmae, const std::string& followee_username) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->FollowWithUsername(req_id, user_usernmae, followee_username);
    }
    ifaces_[i]->FollowWithUsername(req_id, user_usernmae, followee_username);
  }

  void GetFollowees(std::vector<int64_t> & _return, const int64_t req_id, const int64_t user_id) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->GetFollowees(_return, req_id, user_id);
    }
    ifaces_[i]->GetFollowees(_return, req_id, user_id);
    return;
  }

  void ReadHomeTimeline(std::vector<Post> & _return, const int64_t req_id, const int64_t user_id, const int32_t start, const int32_t stop) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->ReadHomeTimeline(_return, req_id, user_id, start, stop);
    }
    ifaces_[i]->ReadHomeTimeline(_return, req_id, user_id, start, stop);
    return;
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class ComposePostServiceConcurrentClient : virtual public ComposePostServiceIf {
 public:
  ComposePostServiceConcurrentClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  ComposePostServiceConcurrentClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void ComposePost(const int64_t req_id, const std::string& username, const int64_t user_id, const std::string& text, const std::vector<int64_t> & media_ids, const std::vector<std::string> & media_types, const PostType::type post_type);
  int32_t send_ComposePost(const int64_t req_id, const std::string& username, const int64_t user_id, const std::string& text, const std::vector<int64_t> & media_ids, const std::vector<std::string> & media_types, const PostType::type post_type);
  void recv_ComposePost(const int32_t seqid);
  void StorePost(const int64_t req_id, const Post& post);
  int32_t send_StorePost(const int64_t req_id, const Post& post);
  void recv_StorePost(const int32_t seqid);
  void ReadPost(Post& _return, const int64_t req_id, const int64_t post_id);
  int32_t send_ReadPost(const int64_t req_id, const int64_t post_id);
  void recv_ReadPost(Post& _return, const int32_t seqid);
  void ReadPosts(std::vector<Post> & _return, const int64_t req_id, const std::vector<int64_t> & post_ids);
  int32_t send_ReadPosts(const int64_t req_id, const std::vector<int64_t> & post_ids);
  void recv_ReadPosts(std::vector<Post> & _return, const int32_t seqid);
  void ReadUserTimeline(std::vector<Post> & _return, const int64_t req_id, const int64_t user_id, const int32_t start, const int32_t stop);
  int32_t send_ReadUserTimeline(const int64_t req_id, const int64_t user_id, const int32_t start, const int32_t stop);
  void recv_ReadUserTimeline(std::vector<Post> & _return, const int32_t seqid);
  void Login(std::string& _return, const int64_t req_id, const std::string& username, const std::string& password);
  int32_t send_Login(const int64_t req_id, const std::string& username, const std::string& password);
  void recv_Login(std::string& _return, const int32_t seqid);
  void RegisterUser(const int64_t req_id, const std::string& first_name, const std::string& last_name, const std::string& username, const std::string& password);
  int32_t send_RegisterUser(const int64_t req_id, const std::string& first_name, const std::string& last_name, const std::string& username, const std::string& password);
  void recv_RegisterUser(const int32_t seqid);
  void RegisterUserWithId(const int64_t req_id, const std::string& first_name, const std::string& last_name, const std::string& username, const std::string& password, const int64_t user_id);
  int32_t send_RegisterUserWithId(const int64_t req_id, const std::string& first_name, const std::string& last_name, const std::string& username, const std::string& password, const int64_t user_id);
  void recv_RegisterUserWithId(const int32_t seqid);
  void GetFollowers(std::vector<int64_t> & _return, const int64_t req_id, const int64_t user_id);
  int32_t send_GetFollowers(const int64_t req_id, const int64_t user_id);
  void recv_GetFollowers(std::vector<int64_t> & _return, const int32_t seqid);
  void Unfollow(const int64_t req_id, const int64_t user_id, const int64_t followee_id);
  int32_t send_Unfollow(const int64_t req_id, const int64_t user_id, const int64_t followee_id);
  void recv_Unfollow(const int32_t seqid);
  void UnfollowWithUsername(const int64_t req_id, const std::string& user_usernmae, const std::string& followee_username);
  int32_t send_UnfollowWithUsername(const int64_t req_id, const std::string& user_usernmae, const std::string& followee_username);
  void recv_UnfollowWithUsername(const int32_t seqid);
  void Follow(const int64_t req_id, const int64_t user_id, const int64_t followee_id);
  int32_t send_Follow(const int64_t req_id, const int64_t user_id, const int64_t followee_id);
  void recv_Follow(const int32_t seqid);
  void FollowWithUsername(const int64_t req_id, const std::string& user_usernmae, const std::string& followee_username);
  int32_t send_FollowWithUsername(const int64_t req_id, const std::string& user_usernmae, const std::string& followee_username);
  void recv_FollowWithUsername(const int32_t seqid);
  void GetFollowees(std::vector<int64_t> & _return, const int64_t req_id, const int64_t user_id);
  int32_t send_GetFollowees(const int64_t req_id, const int64_t user_id);
  void recv_GetFollowees(std::vector<int64_t> & _return, const int32_t seqid);
  void ReadHomeTimeline(std::vector<Post> & _return, const int64_t req_id, const int64_t user_id, const int32_t start, const int32_t stop);
  int32_t send_ReadHomeTimeline(const int64_t req_id, const int64_t user_id, const int32_t start, const int32_t stop);
  void recv_ReadHomeTimeline(std::vector<Post> & _return, const int32_t seqid);
 protected:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  ::apache::thrift::async::TConcurrentClientSyncInfo sync_;
};

#ifdef _MSC_VER
  #pragma warning( pop )
#endif

} // namespace

#endif
